config/routes.rb
Rails.application.routes.draw do
  get "/:username", to: "users#show", as: "profile"

  resources :invitations, only: %i[ create ]
  resources :attendances, only: %i[ create destroy ]
  resources :events

  devise_for :users
  root "events#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/attendance.rb
class Attendance < ApplicationRecord
  belongs_to :attendee, class_name: "User"
  belongs_to :attended_event, class_name: "Event"
end

app/models/event.rb
class Event < ApplicationRecord
  validates :title, presence: true, length: { maximum: 50 }
  validates :location, presence: true, length: { maximum: 50 }
  validates :event_date, presence: true, comparison: { greater_than: 1.day.from_now, less_than: 1.year.from_now }

  belongs_to :creator, class_name: "User"
  has_many :attendances, foreign_key: :attended_event_id
  has_many :invitations
  has_many :attendees, through: :attendances, source: :attendee
  has_many :invitees, through: :invitations, source: :invitee

  scope :past, -> { where("event_date < ?", DateTime.now) }
  scope :future, -> { where("event_date > ?", DateTime.now) }
end

app/models/invitation.rb
class Invitation < ApplicationRecord
  belongs_to :inviter, class_name: "User"
  belongs_to :invitee, class_name: "User"
  belongs_to :event
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :username, presence: true, length: { in: 3..20 }, uniqueness: true
  validates :email, presence: true, uniqueness: true
  validates :password, presence: true, length: { in: 6..20 }

  has_many :events, foreign_key: :creator_id
  has_many :attendances, foreign_key: :attendee_id
  has_many :attended_events, through: :attendances

  has_many :invitations, foreign_key: :invitee_id, class_name: "Invitation", dependent: :destroy
  has_many :invitees, foreign_key: :inviter_id, class_name: "Invitation", dependent: :destroy

  def invited_to?(event)
    invitations.exists?(event: event)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [ :username ])
  end
end

app/controllers/attendances_controller.rb
class AttendancesController < ApplicationController
  before_action :authenticate_user!, only: [ :create ]

  def create
    @event = Event.find(params[:event_id])

    current_user.attendances.create!(attended_event: @event)
    redirect_back fallback_location: root_url, notice: "Joined successfully!"
  end

  def destroy
    @event = Event.find(params[:id])
    @event.attendees.destroy(current_user)
    redirect_back fallback_location: root_url, notice: "Unjoined successfully!"
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!, only: %i[ new create edit update destroy ]

  def index
    @past_events = Event.past
    @future_events = Event.future
  end

  def new
    @event = current_user.events.build
  end

  def edit
    @event = current_user.events.find(params[:id])
  end

  def show
    @event = Event.find(params[:id])
    @other_users = User.where.not(id: current_user)
  end

  def create
    @event = current_user.events.build(event_params)

    if @event.save
      redirect_to root_url, notice: "Event created successfully!"
    else
      flash.now[:alert] = "Event cannot be created."
      render :new, status: :unprocessable_entity
    end
  end

  def update
    @event = Event.find(params[:id])

    if @event.update(event_params)
      redirect_back fallback_location: root_url, notice: "Event updated succesfully!"
    else
      flash.now[:alert] = "Event cannot be updated."
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @event = Event.find(params[:id])
    @event.destroy
    redirect_to profile_url(username: current_user.username), notice: "Event deleted sucessfully!", status: :see_other
  end

  private

    def event_params
      params.expect(event: [ :title, :location, :details, :event_date ])
    end
end

app/controllers/invitations_controller.rb
class InvitationsController < ApplicationController
  before_action :authenticate_user!
  before_action :verify_invitation_existence, only: [ :create ]

  def create
    @event = Event.find(params[:event])
    @invitee = User.find(params[:invitee])

    current_user.invitees.create!(event: @event, invitee: @invitee)
    redirect_back fallback_location: root_url, notice: "Invited #{@invitee.username} successfully!"
  end

  private

    def verify_invitation_existence
      @event = Event.find(params[:event])
      @invitee = User.find(params[:invitee])

      if @invitee.invited_to?(@event)
        redirect_back fallback_location: root_url, alert: "#{@invitee.username} has already been invited."
      end
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_same_account

  def show
    @user = current_user
    @past_events = current_user.attended_events.where("event_date < ?", DateTime.now)
    @future_events = current_user.attended_events.where("event_date > ?", DateTime.now)
  end

  private

    def require_same_account
      if !user_signed_in? || current_user.username != params[:username]
        redirect_back fallback_location: root_url, alert: "You are not allowed to view that."
      end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/attendances_helper.rb
module AttendancesHelper
end

app/helpers/events_helper.rb
module EventsHelper
  def event_joined?(user, event)
    user.attended_event_ids.include?(event.id)
  end

  def event_creator?(user, event)
    user.id == event.creator_id
  end

  def invited?(event, invitee)
    event.invitees.include?(invitee)
  end
end

app/helpers/invitations_helper.rb
module InvitationsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/_form.html.erb
<% if @event.errors.any? %>
  <div class="event-form__errors">
    <p><%= pluralize(@event.errors.count, "error") %> prohibited this event from being created:</p>
    <ul class="error-list">
      <% @event.errors.each do |error| %>
        <li class="error"><%= error.full_message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= form_with model: @event do |form| %>
  <div class="event-form__label">
    <%= form.label :title %>
  </div>
  <div class="event-form__input">
    <%= form.text_field :title, maxlength: 50 %>
  </div>

  <div class="event-form__label">
    <%= form.label :location %>
  </div>
  <div class="event-form__input">
    <%= form.text_field :location, maxlength: 50 %>
  </div>

  <div class="event-form__label">
    <%= form.label :details %>
  </div>
  <div class="event-form__input">
    <%= form.text_area :details, maxlength: 1000 %>
  </div>

  <div class="event-form__label">
    <%= form.label :event_date %>
  </div>
  <div class="event-form__input">
    <%= form.datetime_field :event_date, min: 1.day.from_now, max: 1.year.from_now, include_seconds: false %>
  </div>

  <div class="event-form__submit">
    <%= form.submit %>
  </div>
<% end %>

app/views/events/_short_event_card.html.erb
<%= link_to event_path(event), class: "event-link" do %>
  <div class="event-card">
    <div class="event-card__side">
      <h4>Creator: <%= event.creator.username %></h4>
      <p>Title: <%= event.title %></p>
      <p>Date: <%= event.event_date.to_formatted_s(:long) %></p>
      <p>Location: <%= event.location %></p>
      <br>
      <p><em>Click for more info.</em></p>
    </div>
  </div>
<% end%>

app/views/events/edit.html.erb
<section class="event-form">
  <div class="event-form__container">
    <h2>Edit Event</h2>
    <%= render partial: "form" %>
  </div>
</section>

app/views/events/index.html.erb
<section class="home">
  <header class="home__header">
    <h1>Find all fun events you can participate on, right here!</h1>
    <%= link_to "Create event", new_event_path, class: "primary-btn" %>
  </header>
  <h4>All events are here.</h4>
  <div class="events-container">
    <div class="events-container__list">
      <p>Past Events:</p>
      <% if @past_events.size.zero? %>
        <p>No events found. Try again later.</p>
      <% else %>
        <% @past_events.each do |event| %>
          <%= render partial: "events/short_event_card", locals: { event: event } %>
        <% end %>
      <% end %>
    </div>

    <div class="events-container__list">
      <p>Future Events:</p>
      <% if @future_events.size.zero? %>
        <p>No events found. Try again later.</p>
      <% else %>
        <% @future_events.each do |event| %>
          <%= render partial: "events/short_event_card", locals: { event: event } %>
        <% end %>
      <% end %>
    </div>
  </div>
</section>

app/views/events/new.html.erb
<section class="event-form">
  <div class="event-form__container">
    <h2>Create Event</h2>
    <%= render partial: "form" %>
  </div>
</section>

app/views/events/show.html.erb
<section class="event-details">
  <div class="event-card">
    <div class="event-card__side">
      <h4>Creator: <%= @event.creator.username %></h4>
      <p>Title: <%= @event.title %></p>
      <p>Date: <%= @event.event_date.to_formatted_s(:long) %></p>
      <p>Location: <%= @event.location %></p>
      <p>Details: <%= @event.details %></p>

      <br>

      <h4>Total attendees: <%= @event.attendees.size %></h4>
      <p>List of attendees:</p>
      <% if @event.attendees.size.zero? %>
        <p>None found.</p>
      <% else %>
        <% @event.attendees.each do |attendee| %>
          <ul>
            <li><%= attendee.username %></li>
          </ul>
        <% end %>
      <% end %>

      <br>
      <% if !user_signed_in? %>
        <p>You must be logged in to join.</p>
      <% elsif @event.event_date.past? %>
        <% if event_joined?(current_user, @event) %>
          <p>You joined this event.</p>
        <% end %>
        <p>This event has ended.</p>
      <% elsif event_joined?(current_user, @event) %>
        <%= button_to "Unjoin", attendance_path(@event), method: :delete, class: "secondary-btn", data: { turbo_confirm: "Are you sure?" } %>
      <% elsif event_creator?(current_user, @event) %>
        <p><em>You own this event.</em></p>
      <% elsif current_user.invited_to?(@event) %>
        <%= button_to "Join", attendances_path(event_id: @event.id), class: "primary-btn" %>
      <% else %>
        <p>You are not invited to this event.</p>
      <% end %>
    </div>

    <div class="event-card__side">
      <% if user_signed_in? && event_creator?(current_user, @event) %>
        <%= link_to "Edit", edit_event_path %>
        <%= link_to "Delete", event_path, data: { turbo_confirm: "Are you sure?", turbo_method: :delete } %>
        <% unless @event.event_date.past? %>
          <div class="user-list-container">
            <h4>Invite users:</h4>
            <ul class="user-list">
              <% @other_users.each do |user| %>
                <li><%= user.username %></li>
                <% if user.invited_to?(@event) %>
                  <%= button_to "Invited", nil, class: "neutral-btn", disabled: true %>
                <% else %>
                  <%= button_to "Invite", invitations_path(event: @event, invitee: user), class: "primary-btn" %>
                <% end %>
              <% end %>
            </ul>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Private Events" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <% if flash[:notice] %>
      <p class="notice"><%= notice %></p>
    <% end %>

    <% if flash[:alert] %>
      <p class="alert"><%= alert %></p>
    <% end %>

    <nav class="navbar">
      <h1 class="navbar__logo">Private Events</h1>
      <div class="navbar__links">
        <%= link_to "Home", root_path, class: "navbar__link" %>
      <% if user_signed_in? %>
        <%= link_to "Profile", profile_path(current_user.username), class: "navbar__link" %>
        <%= link_to "Sign Out", destroy_user_session_path, data: { turbo_method: :delete }, class: "navbar__link"  %>
      <% else %>
        <% unless controller_name == 'sessions' || controller_name == 'registrations' %>
          <%= link_to "Log in", new_user_session_path, class: "navbar__link" %>
          <%= link_to "Sign up", new_user_registration_path, class: "navbar__link"%>
        <% end%>
      <% end %>
      </div>
    </nav>

    <%= yield %>
  </body>
</html>

app/views/users/show.html.erb
<section class="profile">
  <h3>Name: <%= current_user.username %></h3>
  <div class="profile-events">
    <div class="created-events">
      <p>My created events:</p>
      <% if current_user.events.size.zero? %>
        <p>Nothing fun to see here. Try creating an event?</p>
      <% else%>
        <% current_user.events.each do |event| %>
          <%= render partial: "events/short_event_card", locals: { event: event } %>
        <% end %>
      <% end %>
    </div>

    <div class="attended-events">
      <h4>My attended events:</h4>
      <div class="events-container">
        <div class="events-container__list">
          <p>Past Events:</p>
          <% if current_user.events.size.zero? %>
            <p>No past attended events. Try attending an event?</p>
          <% else%>
            <% @past_events.each do |event| %>
              <%= render partial: "events/short_event_card", locals: { event: event } %>
            <% end %>
          <% end %>
        </div>

        <div class="events-container__list">
          <p>Future Events:</p>
          <% if current_user.events.size.zero? %>
            <p>No future events. Try attending an event?</p>
          <% else%>
            <% @future_events.each do |event| %>
              <%= render partial: "events/short_event_card", locals: { event: event } %>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</section>